<<<<<<< HEAD
<?php
/*
 * Please, DO NOT EDIT THIS FILE
*/

define ('DB_USER', "root");
define ('DB_PASSWORD', "root");
define ('DB_DATABASE', "hng_fun");
define ('DB_HOST', "localhost");
||||||| merged common ancestors
<?php
/*
 * Please, DO NOT EDIT THIS FILE
*/

define ('DB_USER', "root");
define ('DB_PASSWORD', "");
define ('DB_DATABASE', "hng_fun");
define ('DB_HOST', "localhost");
=======
<?php

/* DO NOT EDIT THIS FILE! */

define ('DB_USER', "root");
define ('DB_PASSWORD', "");
define ('DB_DATABASE', "hng_fun");
define ('DB_HOST', "localhost");

?>\
>>>>>>> 464ebf7ed0a42c06c757f375fa99f8b3e664fa1e
