#! /bin/sh
touch config.php
cat <<EOT >> config.php
<?php
/*
 * Please, DO NOT EDIT THIS FILE
*/
define ('DB_USER', "root");
define ('DB_PASSWORD', "");
define ('DB_DATABASE', "hngfun");
define ('DB_HOST', "localhost");
?>
EOT
mv config.php ../
