#! /bin/sh
rm ../config.php
rm config.php
touch config.php
cat <<EOT >> config.php
<?php
/*
 * Please, DO NOT EDIT THIS FILE
*/
define ('DB_USER', "hng");
define ('DB_PASSWORD', "hng");
define ('DB_DATABASE', "hng");
define ('DB_HOST', "localhost");
?>
EOT
mv config.php ../
