<?php
/*
 * Please, DO NOT EDIT THIS FILE
*/
define ('DB_USER', "root");
<<<<<<< HEAD
define ('DB_PASSWORD', "ndusunday");
=======
define ('DB_PASSWORD', "root");
>>>>>>> 6519e33cdfa082ba7683570d9135e5e859bc5ede
define ('DB_DATABASE', "hng_fun");
define ('DB_HOST', "localhost");
