<?php
<<<<<<< HEAD
define ('DB_USER', "root");
define ('DB_PASSWORD', "29gE9t*dJ2#2f-BS");
define ('DB_DATABASE', "slayers_db");
=======
/*
 * Please, DO NOT EDIT THIS FILE
*/
define ('DB_USER', "root");
define ('DB_PASSWORD', "");
define ('DB_DATABASE', "hngfun");
>>>>>>> 79349ab158576c0c603d15d180c4484b10aad440
define ('DB_HOST', "localhost");
?>
