<<<<<<< HEAD
-<!DOCTYPE html>
-<html lang="en">
-        <title>Abdulhakeem Adigun Olasupo| HNG4 Internship Profile</title>
-  <head>
-    <!-- Required meta tags -->
-    <meta charset="utf-8">
-    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
-    <meta name="author" content="Abdulhakeem Adigun Olasupo">
-
-    <!-- FONT Styles -->
-    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
-    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald">
-    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open Sans">
-    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
-
-    <!-- Bootstrap CSS -->
-    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css">
-
-    <style>
-            .container {
-        text-align:left;
-        padding:2%;
-    }
-    img {
-        width: 40%;
-        height:auto;
-    } 
-    a {
-        color: inherit;
-        text-decoration:none;
-    }
-    .links {
-        padding:1%;
-    }
-    .color {
-        color:blue;
-    }
-    .footer {
-        text-align: center;
-    }
-    .social {
-        font-size: 130%;
-    }
-
-    /* BOT UI STYLE */
-       }#bot {
-           text-align:center
-       }
-
-        .messenger-boxed .card{
-            width: 100%;
-         margin: 0 auto;
-        }
-        .messenger-boxed.col-xs-12 {
-            left: 10px;
-        }
-
-        .messenger-boxed>div>.panel {
-            border-radius: 5px 5px 0 0;
-        }
-
-        .reacher {
-            padding: 2px 10px;
-        }
-
-        .messenger-dez {
-            background: #17a2b8;
-            margin: 0 auto;
-            width: 100%;
-            padding: 0 10px 10px;
-            max-height: 350px;
-            overflow-x: hidden;
-        }
-        /* .messenger_dezs{
-            width:100%;
-        } */
-        .bot-head {
-            padding: 10px;
-            position: relative;
-             overflow: hidden;
-        }
-
-        .outbox-msg {
-            padding-left: 0;
-            margin-left: 0;
-            background: #00b2c5 !important;
-            color: #FFF;
-        }
-
-        .inbox-message {
-            padding-bottom: 20px !important;
-            margin-right: 0;
-            
-        }
-
-        .responses {
-            background: white;
-            padding: 10px;
-            border-radius: 2px;
-            box-shadow: 0 1px 2px rgba(0, 0, 0, 0.2);
-            max-width: 80%;
-        }
-
-        .responses>p {
-            font-size: 13px;
-            margin: 0 0 0.2rem 0;
-            overflow-wrap: break-word;
-        }
-
-        .responses>time {
-            font-size: 11px;
-            color: #ccc;
-        }
-
-        .messenger-dezs {
-            padding: 10px;
-            overflow: hidden;
-            display: flex;
-        }
-
-        .response-got>.avatar:after {
-            content: "";
-            position: absolute;
-            top: 0;
-            right: 0;
-            width: 0;
-            height: 0;
-            border-left-color: rgba(0, 0, 0, 0);
-            border-bottom-color: rgba(0, 0, 0, 0);
-        }
-
-        .response-sent {
-            justify-content: flex-end;
-            align-items: flex-end;
-
-        }
-
-        .response-sent>.avatar:after {
-            content: "";
-            position: absolute;
-            bottom: 0;
-            left: 0;
-            width: 0;
-            height: 0;
-            border: 5px solid white;
-            border-right-color: transparent;
-            border-top-color: transparent;
-            box-shadow: 1px 1px 2px rgba(black, 0.2); // not quite perfect but close } .inbox_msg > time{
-            float: right;
-        }
-
-        .messenger-dez::-webkit-scrollbar-track {
-            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, 0.3);
-            background-color: #F5F5F5;
-        }
-
-        .messenger-dez::-webkit-scrollbar {
-            width: 12px;
-            background-color: #F5F5F5;
-        }
-
-        .messenger-dez::-webkit-scrollbar-thumb {
-            -webkit-box-shadow: inset 0 0 6px rgba(0, 0, 0, .3);
-            background-color: #555;
-        }
-
-        .messengerbody{
-
-           border-radius: 20px;
-            max-width: 90%;
-            margin: 0 auto;
-            margin-bottom: 50px;
-
-        }
-
-        .iconn:hover{
-            color: #00AEFF !important;
-        }
-        .icon-container{
-            padding: 20px;
-        }
-        .connect{
-
-            color:red !important;
-            padding: 10px 0;
-        }
-
-        #intro{
-            padding: 0 20px;
-        }
-    </style>
-
-           </head>
-       <!-- BODY SECTION -->
-
-        <body class="bg-dark text-light">
-        <br /><br /><br />
-            <div class="row">
-        <div class="col-sm bg-dark text-light">
-            <br />
-                <img class="rounded-circle" style="width:60%" src="http://res.cloudinary.com/digital4us/image/upload/v1525988624/Webp.net-resizeimage_1.jpg" alt="My Picture">
-                <br /><br /><br />
-                         <p> Hello World! <br />
-            I'm ABDULHAKEEM OLASUPO|<br />
-            Tech Geek <i class="fa fa-user text-primary"></i>&nbsp & Web Developer <i class="fa fa-laptop text-primary"></i></p>
-            <br />
-            
-        </div> 
-
-                <div class="col-sm bg-dark">
-                <br /><br />
-            <div class="social">
-            <br /><br /><br /><br /><br />
-            
-                    <a class="navbar-brand btn btn-outline-primary" href="#">Contact Me!</a>
-        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
-          <span class="navbar-toggler-icon"></span>
-        </button>
-                    <br /> <br />
-                    
-                     <div class="text-light">
-                      <p><i class="fa fa-map-marker text-primary"></i> Osun, Nigeria</p>
-                      <p><i class="fa fa-phone text-primary"></i> +234 8141734905</p>
-                      <p><i class="fa fa-envelope text-primary"> </i> olasupoabdulhakeem2002@gmail.com</p>
						<p><i class="fa fa-map-marker text-primary"></i> digitalforus.wordpress.com</p>
						<p><i class="fa fa-map-marker text-primary"></i> digitalus.intelaedu.com</p>-                      
-                <a href="https://github.com/prodigy" style="text-decoration:none"
-                class="fa fa-github social text-light"></a>&nbsp
-                <a href="https://medium.com/@BolajiAyodeji" style="text-decoration:none"
-                class="fa fa-medium social text-light"></a>&nbsp
-                <a href="https://slack.com/hnginternship4" style="text-decoration:none"
-                class="fa fa-slack social text-light"></a>&nbsp
-                <a href="https://facebook.com/Hakeem Olasupo" style="text-decoration:none"
-                class="fa fa-facebook-official social text-light"></a>&nbsp
-                <a href="https://instagram.com/hakeemolasupo09" style="text-decoration:none"
-                class="fa fa-instagram social text-light"></a>&nbsp
-                <a href="https://twitter.com/hakeemolasupo09" style="text-decoration:none"
-                class="fa fa-twitter social text-light"></a>&nbsp
-                <a href="https://linkedin.com/in/Olasupo Hakeem" style="text-decoration:none"
-                class="fa fa-linkedin social text-light"></a>&nbsp
-                <a href="https://whatsapp.com/08141734905" style="text-decoration:none"
-                class="fa fa-whatsapp social text-light"></a>&nbsp
-                <br /><br />
-                <a class="navbar-brand btn btn-danger" href="#bot">Lets Chat!<i class="fa fa-rocket"></i></a>
-        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
-          <span class="navbar-toggler-icon"></span>
-        </button>
-
-                <div="" id="bot">
-                <br /><br />
-                           
-                </div></div></div></div>
-                <br />
-                
-        <div class="row" align="center">                 
-        <div class="col-md bg-dark text-dark">
-            <br>
-		<div class="col-md-12 no-padding">
-		<div class="col-lg-4 col-sm|md|xs-10">
-        <div class="card">
-        <div class="bot-head bg-light text-muted">
-        <div class="col-md-8 col-xs-8">
-        <img src="http://res.cloudinary.com/digital4us/image/upload/v1525988624/Webp.net-resizeimage_1.jpg"> <h4> Digital4ua Bot </h4>
-        </div></div>
</body>
 </html>